## C:\ENI_Angular\PokemonManager\.travis.yml ##

# Langage de programmation utilisé
language: node_js
# Version du langage
node_js:
  - "12"

# Distribution Linux utilisée
dist: trusty
# Les commandes nécessitent-elles sudo ?
sudo: required

# Git clone silencieux
git:
  quiet: true

# Quelles branches sont à surveiller ?
Branches:
  only:
    - master
