## /Users/Daphne/Documents/projets-angular/LighthouseCi/.travis.yml ##

# Langage de programmation utilisé
language: node_js
# Version du langage
node_js:
  - "12"

# Distribution Linux utilisée
dist: trusty
# Les commandes nécessitent-elles d'être superutilisateur ?
sudo: required
